stages:
  - basic_checks

image: mcr.microsoft.com/dotnet/sdk:8.0

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  ASPNETCORE_ENVIRONMENT: "Development"

checkstyle:
  stage: basic_checks
  script:
    - dotnet format --verify-no-changes
  allow_failure: false  
  only:
    - merge_requests
    - branches

test:
  stage: basic_checks
  script:
    - cd IDsas.Server.Test
    - dotnet test --verbosity normal --collect:"XPlat Code Coverage"
  artifacts:
    when: always
    reports:
      junit: TestResults.xml
      coverage_report:
        coverage_format: cobertura
        path: TestResults/coverage.cobertura.xml
  only:
    - merge_requests
    - branches