// <auto-generated />
using System;
using IDsas.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IDsas.Server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241025150019_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("IDsas.Server.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("IDsas.Server.Entities.DocumentLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssociatedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LinkType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedUserId");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentLinks");
                });

            modelBuilder.Entity("IDsas.Server.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorizationToken")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IDsas.Server.Entities.Document", b =>
                {
                    b.HasOne("IDsas.Server.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("IDsas.Server.Entities.DocumentLink", b =>
                {
                    b.HasOne("IDsas.Server.Entities.User", "AssociatedUser")
                        .WithMany()
                        .HasForeignKey("AssociatedUserId");

                    b.HasOne("IDsas.Server.Entities.Document", "Document")
                        .WithMany("DocumentLinks")
                        .HasForeignKey("DocumentId");

                    b.Navigation("AssociatedUser");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("IDsas.Server.Entities.Document", b =>
                {
                    b.Navigation("DocumentLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
